from fastapi import APIRouter, UploadFile, File, HTTPException
from fastapi.responses import FileResponse
import os
import shutil

router = APIRouter()

# Directory to store sanction letters
SANCTION_DIR = os.path.join(os.path.dirname(__file__), "..", "generated", "sanction_letters")
os.makedirs(SANCTION_DIR, exist_ok=True)

@router.post("/upload-sanction/{session_id}")
async def upload_sanction_letter(session_id: str, file: UploadFile = File(...)):
    """
    Receives the client-generated PDF sanction letter and saves it.
    This ensures the Admin Dashboard downloads the exact same file the user sees.
    """
    try:
        file_location = os.path.join(SANCTION_DIR, f"{session_id}.pdf")
        with open(file_location, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        return {"status": "success", "message": "Sanction letter uploaded successfully", "path": file_location}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/download-sanction/{session_id}")
async def download_sanction_letter(session_id: str):
    """
    Serves the sanction letter PDF for the given session ID.
    Used by the Admin Dashboard.
    """
    file_location = os.path.join(SANCTION_DIR, f"{session_id}.pdf")
    
    # Check if the PDF exists (uploaded from client)
    if os.path.exists(file_location):
        return FileResponse(file_location, media_type="application/pdf", filename=f"Sanction_Letter_{session_id}.pdf")
    
    # Fallback: Check if there is an HTML file generated by the agent (legacy/backup)
    html_location = os.path.join(SANCTION_DIR, f"{session_id}.html") # SanctionAgent uses Ref No, but let's check standardized ID too or just fail for now
    
    # Note: SanctionAgent saves as {Reference_Number}.html, not session_id. 
    # Since we are standardizing on the Client PDF, we primarily look for the PDF.
    
    raise HTTPException(status_code=404, detail="Sanction letter not found. User may not have reached this stage or upload failed.")
