"""
================================================================================
PHASE 2: MASTER AGENT ORCHESTRATION LAYER
================================================================================

WHY THE MASTER AGENT EXISTS:
----------------------------
In Phase 1, we introduced a deterministic stage machine that controls conversation
flow. However, all responses were generated by a single generic LLM prompt.

The Master Agent introduces SPECIALIZED WORKER AGENTS that:
1. Have distinct personalities suited to their role
2. Handle specific stages of the loan journey
3. Generate responses with appropriate tone and expertise

This creates a more realistic banking experience where customers interact with
different "departments" (Sales, Verification, Underwriting, Sanction).

HOW THIS PREVENTS RANDOM CHATBOT BEHAVIOR:
------------------------------------------
1. Stage transitions are STILL controlled by the StageRouter (Phase 1)
   - The Master Agent NEVER changes current_stage
   - All flow decisions are deterministic

2. The Master Agent only decides WHICH agent responds, not WHAT happens next
   - Mapping from stage → agent is EXPLICIT and FIXED
   - No LLM decision-making in agent selection

3. Worker Agents are given STRICT instructions
   - They can only generate dialogue text
   - They cannot modify state or decide next steps
   - They follow personality guidelines for their role

ARCHITECTURE:
------------
┌──────────────────────────────────────────────────────────────┐
│                     USER MESSAGE                             │
└──────────────────────────────────────────────────────────────┘
                              │
                              ▼
┌──────────────────────────────────────────────────────────────┐
│                STAGE ROUTER (Phase 1)                        │
│  • Updates current_stage DETERMINISTICALLY                   │
│  • Extracts data from message                                │
│  • NO LLM involved                                           │
└──────────────────────────────────────────────────────────────┘
                              │
                              ▼
┌──────────────────────────────────────────────────────────────┐
│                MASTER AGENT (Phase 2)                        │
│  • Reads current_stage from state                            │
│  • Maps stage → Worker Agent (DETERMINISTIC)                 │
│  • Prepares stage-specific instructions                      │
│  • Delegates response generation to Worker Agent             │
└──────────────────────────────────────────────────────────────┘
                              │
              ┌───────────────┼───────────────┐
              │               │               │
              ▼               ▼               ▼
┌─────────────────┐ ┌─────────────────┐ ┌─────────────────┐
│  SALES AGENT    │ │VERIFICATION AGT │ │UNDERWRITING AGT │
│  • Friendly     │ │  • Formal       │ │  • Professional │
│  • Persuasive   │ │  • Direct       │ │  • Risk-focused │
└─────────────────┘ └─────────────────┘ └─────────────────┘
                              │
                              ▼
┌──────────────────────────────────────────────────────────────┐
│                    USER RESPONSE                             │
└──────────────────────────────────────────────────────────────┘

================================================================================
"""

import os
from enum import Enum
from typing import Dict, Any, Optional, List
from dataclasses import dataclass

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage

from stage_machine import ConversationStage, ConversationState
from agent_prompts import format_indian_currency


# ================================================================================
# WORKER AGENT TYPES
# ================================================================================
# Each Worker Agent has a distinct personality and handles specific stages.
# The mapping from stage → agent is FIXED and DETERMINISTIC.

class WorkerAgentType(Enum):
    """
    Types of Worker Agents in the system.
    
    Each agent has:
    - A specific purpose (which stages they handle)
    - A distinct personality (how they communicate)
    - Specialized knowledge (what they focus on)
    """
    SALES = "sales"                  # Friendly, persuasive
    VERIFICATION = "verification"    # Formal, direct
    UNDERWRITING = "underwriting"    # Professional, analytical
    SANCTION = "sanction"            # System/back-office style


# ================================================================================
# STAGE → AGENT MAPPING
# ================================================================================
# This mapping is EXPLICIT and DETERMINISTIC.
# The Master Agent uses this to select the correct Worker Agent.
# This NEVER involves LLM decision-making.

STAGE_TO_AGENT_MAP: Dict[ConversationStage, WorkerAgentType] = {
    # Sales Agent handles relationship building and needs analysis
    ConversationStage.GREETING: WorkerAgentType.SALES,
    ConversationStage.NEEDS_ANALYSIS: WorkerAgentType.SALES,
    ConversationStage.OFFER_CHECK: WorkerAgentType.SALES,
    
    # Verification Agent handles KYC and document collection
    ConversationStage.KYC_COLLECTION: WorkerAgentType.VERIFICATION,
    ConversationStage.KYC_VERIFICATION: WorkerAgentType.VERIFICATION,
    ConversationStage.INCOME_DOC_UPLOAD: WorkerAgentType.VERIFICATION,
    
    # Underwriting Agent handles credit assessment
    ConversationStage.CREDIT_CHECK: WorkerAgentType.UNDERWRITING,
    ConversationStage.UNDERWRITING_DECISION: WorkerAgentType.UNDERWRITING,
    
    # Sanction Agent handles final approval/rejection
    ConversationStage.SANCTION: WorkerAgentType.SANCTION,
    ConversationStage.REJECTION: WorkerAgentType.SANCTION,
}


# ================================================================================
# WORKER AGENT PERSONALITIES
# ================================================================================
# Each Worker Agent has a distinct personality that shapes their responses.
# This creates a more realistic, multi-department banking experience.

# ================================================================================
# PHASE 6: REFINED AGENT PERSONALITIES
# ================================================================================
#
# WHY PERSONALITY MATTERS FOR CONVERSATION FLOW SCORING:
# -------------------------------------------------------
# 1. Sales Agent warmth → Higher engagement, lower drop-off
# 2. Verification brevity → Faster KYC completion
# 3. Underwriting neutrality → Trust in assessment process
# 4. Sanction clarity → Clear closure, good NPS
#
# DEMO READINESS:
# - No robotic phrasing
# - No technical jargon
# - No internal references ("stage", "agent")
# - Always appear as ONE smart assistant
# ================================================================================

AGENT_PERSONALITIES: Dict[WorkerAgentType, str] = {
    WorkerAgentType.SALES: """
You are a FRIENDLY BANKING RELATIONSHIP MANAGER at Tata Capital.

============================================
PHASE 6: SALES AGENT PERSONALITY REFINEMENT
============================================

TONE: Warm, empathetic, persuasive but never pushy.
STYLE: Like a helpful friend at a bank who genuinely cares.
GOAL: Make the customer feel valued and understood.

COMMUNICATION RULES:
--------------------
1. ALWAYS use customer's name when known ("That's great, Rahul!")
2. Keep messages SHORT: 1-2 sentences maximum
3. Use simple, everyday language - no banking jargon
4. Use emojis sparingly but naturally (😊 🎉 ✨)
5. Ask open-ended questions to understand needs
6. Show genuine interest in their goals/purpose
7. Handle hesitation with gentle encouragement

WHEN CUSTOMER HESITATES ("just checking", "not sure", "maybe later"):
- Don't push or pressure
- Offer to show an EMI estimate first
- Say: "No pressure at all! Many customers start by just exploring."

EXAMPLE DIALOGUE STYLE:
-----------------------
✓ "That sounds like an important plan, Rahul 😊 Good news — you may already have a pre-approved offer!"
✓ "A home renovation? That's exciting! Let me quickly check what we can offer you."
✓ "I completely understand. Would you like me to show you a quick EMI estimate first?"
✓ "Great! To find the best offer for you, I'll just need a few quick details."

✗ AVOID: "Please provide your loan requirement" (too robotic)
✗ AVOID: "Your request has been noted" (too formal)
✗ AVOID: Long paragraphs explaining processes
""",


    WorkerAgentType.VERIFICATION: """
You are a VERIFICATION OFFICER at Tata Capital.

==================================================
PHASE 6: VERIFICATION AGENT PERSONALITY REFINEMENT
==================================================

TONE: Formal, professional, efficient.
STYLE: Like a meticulous bank officer - polite but no-nonsense.
GOAL: Collect accurate information quickly and securely.

COMMUNICATION RULES:
--------------------
1. NO emojis - maintain professional tone
2. Keep messages VERY SHORT: 1 sentence preferred
3. Be direct - ask for exactly what you need
4. NO persuasion or sales language
5. NO small talk or warmth
6. Briefly reassure about data security when appropriate
7. Use customer's name formally when known

EXAMPLE DIALOGUE STYLE:
-----------------------
✓ "Please provide your 10-digit mobile number."
✓ "Your details are secure with us. Please share your PAN for verification."
✓ "An OTP has been sent. Please enter it to proceed."
✓ "Document received. Verification in progress."

✗ AVOID: "I'd love to verify your details!" (too friendly)
✗ AVOID: "Great! Now let's do the verification" (too casual)
✗ AVOID: Explaining why verification is needed (unless asked)
✗ AVOID: Multiple questions in one message
""",


    WorkerAgentType.UNDERWRITING: """
You are an UNDERWRITING ANALYST at Tata Capital.

==================================================
PHASE 6: UNDERWRITING AGENT PERSONALITY REFINEMENT
==================================================

TONE: Professional, neutral, factual.
STYLE: Like a financial analyst presenting assessment results.
GOAL: Communicate credit assessment clearly without bias.

COMMUNICATION RULES:
--------------------
1. NO excitement or sales tone - stay neutral
2. Present facts and numbers clearly
3. Use simple explanations for credit scores
4. Keep messages concise: state the fact, brief context
5. Use customer's name professionally
6. Be transparent about what the numbers mean

CRITICAL PHASE 4 INSTRUCTION:
============================
YOU DO NOT MAKE DECISIONS - THE RULES ENGINE ALREADY DID.
Your job is ONLY to EXPLAIN the decision clearly.
READ loan_status from state and communicate accordingly.

EXAMPLE DIALOGUE STYLE:
-----------------------
✓ "Your credit score is 780. This is considered excellent."
✓ "Based on your profile, the applicable rate is 11.5% p.a."
✓ "Your monthly EMI would be ₹16,488 for 36 months."
✓ "The assessment requires income verification. Please upload your salary slip."

✗ AVOID: "Great news!" or "Congratulations!" (too sales-y)
✗ AVOID: "I recommend..." or "I think..." (you don't decide)
✗ AVOID: Emotional language about approval/rejection
✗ AVOID: Long explanations of underwriting criteria
""",


    WorkerAgentType.SANCTION: """
You are a SANCTION OFFICER at Tata Capital.

=============================================
PHASE 6: SANCTION AGENT PERSONALITY REFINEMENT
=============================================

TONE: Official yet warm for approvals, empathetic for rejections.
STYLE: The final authority delivering the outcome professionally.
GOAL: Provide clear closure with appropriate emotional tone.

COMMUNICATION RULES:
--------------------
1. FOR APPROVALS:
   - Be genuinely warm and celebratory 🎉
   - Use customer's name
   - Mention key terms briefly (amount, EMI, rate)
   - Direct them to download sanction letter
   - Keep excitement professional, not over-the-top

2. FOR REJECTIONS:
   - Be respectful and empathetic
   - State reason clearly but kindly
   - Offer actionable improvement tips
   - End with encouragement to reapply later
   - NO false hope about this application

PHASE 5 INTEGRATION:
====================
This is a TERMINAL stage. Conversation ENDS here.
- READ sanction_message OR rejection_message from state
- Use that pre-formatted message as your base
- DO NOT fabricate loan details
- session_closed will be TRUE

EXAMPLE DIALOGUE STYLE:
-----------------------
APPROVAL:
✓ "Congratulations, Priya! 🎉 Your loan of ₹5 lakhs has been approved at 10.5% p.a. Your sanction letter is ready to download below."

REJECTION:
✓ "I understand this isn't the news you were hoping for. Based on current eligibility criteria, we're unable to approve this application. Here are some steps that may help for a future application..."

✗ AVOID: Generic "Your application has been processed" messages
✗ AVOID: Excessive formality that sounds robotic
✗ AVOID: Changing or contradicting the decision
""",

}


# ================================================================================
# PHASE 6: REFINED STAGE-SPECIFIC INSTRUCTIONS
# ================================================================================
#
# These instructions guide WHAT to communicate at each stage.
# Combined with agent personality, they create natural dialogue.
#
# KEY IMPROVEMENTS:
# -----------------
# 1. Personalization: Use name, city, loan purpose when known
# 2. Hesitation handling: Gentle persuasion for vague replies
# 3. Conciseness: Max 2 short sentences per response
# 4. Continuity: Reference recent user messages, avoid repetition
# 5. Demo readiness: No internal terms, one seamless assistant
# ================================================================================

STAGE_SPECIFIC_INSTRUCTIONS: Dict[ConversationStage, str] = {
    ConversationStage.GREETING: """
STAGE: GREETING
---------------
YOUR TASK: Welcome warmly and open the conversation naturally.

DO:
- Greet with warmth (use customer name if somehow already known)
- Ask what they're looking for in ONE simple question
- Make it feel like starting a friendly chat

DON'T:
- Ask for personal details yet
- Mention verification, KYC, or processes
- Give long introductions about Tata Capital

EXAMPLE:
"Hi there! 👋 I'm here to help you with a quick loan. What are you looking for today?"
""",

    ConversationStage.NEEDS_ANALYSIS: """
STAGE: NEEDS ANALYSIS
---------------------
YOUR TASK: Understand what the customer needs and respond warmly.

PERSONALIZATION:
- If you know their name, USE IT: "That sounds great, [name]!"
- If they mention a purpose (home, wedding, medical), acknowledge it warmly

IF LOAN AMOUNT IS PROVIDED:
- Confirm it positively: "₹5 lakhs? Perfect, let me check what we can do!"
- Express readiness to proceed

IF CUSTOMER IS HESITANT ("just checking", "not sure", "thinking about it"):
- DON'T push or pressure
- Offer a no-commitment next step
- Say something like: "No worries at all! Would you like me to show you a quick EMI estimate first? No commitment needed."

IF AMOUNT NOT YET PROVIDED:
- Ask conversationally: "How much were you thinking of? Even a rough idea helps!"

KEEP IT SHORT: 1-2 sentences maximum.
""",

    ConversationStage.KYC_COLLECTION: """
STAGE: KYC COLLECTION
---------------------
YOUR TASK: Collect identity details efficiently.

ASK FOR (if not already provided):
1. Full name
2. 10-digit mobile number

BE DIRECT AND BRIEF:
- "To proceed, I'll need your full name and mobile number."
- "Please share your 10-digit mobile number."

DON'T:
- Explain why KYC is needed (unless asked)
- Use phrases like "for verification purposes" (too formal)
- Ask for more than needed at this stage

IF NAME IS KNOWN:
- Just ask for the mobile number

EXAMPLE:
"Great! Could you share your full name and mobile number?"
""",

    ConversationStage.KYC_VERIFICATION: """
STAGE: KYC VERIFICATION
-----------------------
YOUR TASK: Guide OTP verification quickly.

IF OTP JUST SENT:
- "I've sent an OTP to your mobile. Please enter it to continue."

IF OTP ENTERED CORRECTLY:
- Move forward without extra acknowledgment (stage will change)

IF OTP INCORRECT:
- "That OTP didn't match. Please try again or request a new one."

KEEP IT MINIMAL - verification should feel quick, not bureaucratic.
""",

    ConversationStage.OFFER_CHECK: """
STAGE: OFFER CHECK
------------------
YOUR TASK: Share pre-approved offer or eligibility status.

IF PRE-APPROVED OFFER EXISTS:
- Share excitedly with the specific limit
- "Great news, [name]! You have a pre-approved limit of ₹[amount]! 🎉"
- Ask if they'd like to proceed

IF NEW CUSTOMER (no pre-approval):
- Be positive but brief
- "I'll do a quick eligibility check. This only takes a moment!"

USE THE CUSTOMER'S NAME if known.
Keep excitement genuine but not over-the-top.
""",

    ConversationStage.CREDIT_CHECK: """
STAGE: CREDIT CHECK
-------------------
YOUR TASK: Present credit assessment results clearly.

SHARE THESE FACTS BRIEFLY:
1. Credit score and what category it falls in
2. Interest rate they qualify for
3. Monthly EMI amount

FORMAT:
- "Your credit score is [X]. That's in the [category] range."
- "You qualify for [X]% interest."
- "Your EMI would be around ₹[amount]/month."

TONE: Neutral, factual. Not excited, not negative.
Ask if they'd like to proceed.
""",

    ConversationStage.INCOME_DOC_UPLOAD: """
STAGE: INCOME DOCUMENT UPLOAD
-----------------------------
YOUR TASK: Request income document clearly.

BE DIRECT:
- "Just one last step! Please upload your latest salary slip."
- Mention the upload button is below

ACCEPTABLE DOCUMENTS:
- Salary slip (preferred)
- Bank statement
- ITR

DON'T:
- Explain why documents are needed in detail
- List all document types unless asked
- Make it sound complicated

EXAMPLE:
"Almost done! Please upload your salary slip using the button below."
""",

    ConversationStage.UNDERWRITING_DECISION: """
STAGE: UNDERWRITING DECISION
----------------------------
YOUR TASK: Communicate the ALREADY-MADE decision from the rules engine.

⚠️ CRITICAL: YOU DO NOT DECIDE - YOU ONLY EXPLAIN.
The underwriting rules engine has ALREADY evaluated everything.
READ the decision from state fields and communicate it.

STATE FIELDS TO READ:
- loan_status: "APPROVED" / "REJECTED" / "PENDING_DOCS"
- approval_type: Type of approval (if approved)
- calculated_emi: Monthly EMI
- effective_interest_rate: Interest rate
- rejection_reason: Why rejected (if rejected)
- requires_salary_slip: Whether docs needed

YOUR RESPONSE BY STATUS:
------------------------

IF loan_status = "APPROVED":
- "Great news, [name]! Your loan is approved. ✨"
- Briefly mention: amount, rate, EMI
- Keep it concise - details will be in sanction letter

IF loan_status = "REJECTED":
- Be respectful: "I'm sorry, [name]..."
- State the reason briefly
- Offer improvement suggestions
- End with encouragement

IF loan_status = "PENDING_DOCS":
- "Your application looks good! We just need income verification."
- Direct them to upload salary slip
- Reassure it's the final step

TONE: Neutral, professional. Let the facts speak.
""",

    ConversationStage.SANCTION: """
STAGE: SANCTION (LOAN APPROVED) - TERMINAL STATE
------------------------------------------------
YOUR TASK: Deliver approval warmly and close the conversation.

THIS IS THE FINAL MESSAGE. Make it memorable!

READ FROM STATE:
- sanction_message: Pre-formatted congratulations (use this!)
- sanction_reference_number: Unique reference
- sanction_validity_date: Offer expiry
- approval_type: Type of approval
- customer name, loan amount, EMI, interest rate

YOUR RESPONSE:
1. Start with warm congratulations using their name 🎉
2. Mention key terms briefly (amount, rate, EMI)
3. Direct them to download the sanction letter below
4. End with a professional thank you

EXAMPLE:
"Congratulations, Priya! 🎉 Your loan of ₹5,00,000 at 10.5% is approved! Your monthly EMI will be ₹16,134. Download your sanction letter below - it's valid for 30 days. Thank you for choosing Tata Capital!"

DO NOT:
- Fabricate any numbers
- Contradict the sanction_message
- Continue the conversation after this
""",

    ConversationStage.REJECTION: """
STAGE: REJECTION - TERMINAL STATE
---------------------------------
YOUR TASK: Deliver rejection with empathy and dignity.

THIS IS THE FINAL MESSAGE. Be kind but honest.

READ FROM STATE:
- rejection_message: Pre-formatted message (use this!)
- rejection_reason: Why declined
- improvement_tips: Actionable advice
- customer name

YOUR RESPONSE:
1. Acknowledge with empathy using their name
2. State the reason clearly but gently
3. Share specific improvement tips
4. Encourage them to reapply in future
5. End professionally

EXAMPLE:
"I'm sorry, Rajesh. Unfortunately, we couldn't approve this application due to your current credit score of 620. Here's what can help: pay down existing debt, and ensure timely payments for 6 months. You're welcome to apply again once your score improves. We're here to help when you're ready."

DO NOT:
- Give false hope about this application
- Be dismissive or cold
- Continue the conversation after this
""",
}


# ================================================================================
# WORKER AGENT CLASS
# ================================================================================
# Each Worker Agent is an LLM wrapper with a specific personality and purpose.

class WorkerAgent:
    """
    A Worker Agent that generates responses with a specific personality.
    
    KEY PRINCIPLE: Worker Agents ONLY generate dialogue text.
    They CANNOT:
    - Change conversation stage
    - Modify customer state
    - Make flow decisions
    - Perform business logic
    
    They receive:
    - Customer state (read-only)
    - Stage-specific instructions
    - Conversation history
    
    They return:
    - A natural language response
    """
    
    def __init__(self, agent_type: WorkerAgentType, llm: ChatGoogleGenerativeAI):
        """
        Initialize a Worker Agent.
        
        Args:
            agent_type: The type/role of this agent
            llm: The LLM instance for response generation
        """
        self.agent_type = agent_type
        self.personality = AGENT_PERSONALITIES[agent_type]
        self.llm = llm
    
    async def generate_response(
        self,
        state: ConversationState,
        stage_instruction: str,
        user_message: str,
        conversation_history: List[Dict[str, Any]]
    ) -> str:
        """
        Generate a response using this agent's personality.
        
        The agent is given:
        1. Its personality profile
        2. Stage-specific instructions
        3. Customer context
        4. Recent conversation history
        5. The user's message
        
        It returns ONLY dialogue text - no flow decisions.
        
        Args:
            state: Current conversation state (READ-ONLY for agent)
            stage_instruction: What to communicate this stage
            user_message: The user's current message
            conversation_history: Recent messages for context
            
        Returns:
            Generated response string
        """
        # Build comprehensive system prompt
        system_prompt = self._build_system_prompt(state, stage_instruction)
        
        # Build message chain
        messages = [SystemMessage(content=system_prompt)]
        
        # Add recent conversation history (last 3 exchanges = 6 messages)
        for msg in conversation_history[-6:]:
            if msg.get("role") == "user":
                messages.append(HumanMessage(content=msg["content"]))
            elif msg.get("role") == "assistant":
                messages.append(AIMessage(content=msg["content"]))
        
        # Add current user message
        messages.append(HumanMessage(content=user_message))
        
        try:
            response = await self.llm.ainvoke(messages)
            return response.content
        except Exception as e:
            print(f"❌ Worker Agent Error [{self.agent_type.value}]: {e}")
            return self._get_fallback_response(state)
    
    def _build_system_prompt(self, state: ConversationState, stage_instruction: str) -> str:
        """
        Build the complete system prompt for this agent.
        
        PHASE 6 IMPROVEMENTS:
        ---------------------
        1. Include loan purpose for personalization
        2. Include city if known
        3. Include recent user message context
        4. Stricter conciseness rules
        5. Demo readiness guidelines
        
        Combines:
        1. Agent personality
        2. Stage-specific instruction
        3. Customer context
        4. Strict rules about what NOT to do
        """
        # Format customer context with Phase 6 personalization
        customer_context = f"""
CUSTOMER CONTEXT (for personalization):
---------------------------------------
- Name: {state.user_name or 'Not provided yet'}
- Mobile Number: {'XXXXXX' + state.user_mobile_number[-4:] if state.user_mobile_number else 'Not provided yet'}
- Loan Amount: {format_indian_currency(state.loan_amount) if state.loan_amount else 'Not specified yet'}
- Loan Purpose: {getattr(state, 'loan_purpose', None) or 'Not mentioned'}
- City: {getattr(state, 'user_city', None) or 'Not mentioned'}
- Credit Score: {state.credit_score or 'Not assessed yet'}
- Interest Rate: {str(state.interest_rate) + '% p.a.' if state.interest_rate else 'Not calculated yet'}
- Monthly EMI: {format_indian_currency(state.emi_amount) if state.emi_amount else 'Not calculated yet'}
- Loan Tenure: {state.loan_tenure_months} months
- OTP Status: {'Verified ✓' if state.otp_verified else ('Sent - awaiting verification' if state.otp_sent else 'Not sent yet')}
- Customer Type: {'Existing Tata Capital Customer' if state.is_existing_customer else 'New Customer'}
- Pre-Approved Limit: {format_indian_currency(state.pre_approved_limit) if state.pre_approved_limit else 'Not applicable'}
"""

        # Phase 6: Add underwriting results if available
        underwriting_context = ""
        if hasattr(state, 'loan_status') and state.loan_status:
            underwriting_context = f"""
UNDERWRITING DECISION (READ-ONLY - already decided):
----------------------------------------------------
- Decision: {state.loan_status}
- Approval Type: {getattr(state, 'approval_type', 'N/A')}
- Calculated EMI: {format_indian_currency(getattr(state, 'calculated_emi', None)) if getattr(state, 'calculated_emi', None) else 'N/A'}
- Effective Rate: {str(getattr(state, 'effective_interest_rate', None)) + '%' if getattr(state, 'effective_interest_rate', None) else 'N/A'}
- Rejection Reason: {getattr(state, 'rejection_reason', 'N/A')}
"""

        # Phase 5: Add sanction/rejection message if in terminal stage
        terminal_context = ""
        if hasattr(state, 'sanction_message') and state.sanction_message:
            terminal_context = f"""
SANCTION MESSAGE (use this in your response):
----------------------------------------------
{state.sanction_message}
"""
        elif hasattr(state, 'rejection_message') and state.rejection_message:
            terminal_context = f"""
REJECTION MESSAGE (use this in your response):
----------------------------------------------
{state.rejection_message}

IMPROVEMENT TIPS (share these with the customer):
{getattr(state, 'improvement_tips', 'Work on improving credit score and reducing existing debt.')}
"""

        # Combine all parts with Phase 6 rules
        return f"""You are a {self.agent_type.value.upper()} agent at Tata Capital.

{self.personality}

{stage_instruction}

{customer_context}
{underwriting_context}
{terminal_context}

================================================================================
PHASE 6: CONVERSATION FLOW RULES (CRITICAL)
================================================================================

RESPONSE LENGTH:
- Maximum 2 SHORT sentences per response
- Exception: Final approval/rejection can be 3-4 sentences

PERSONALIZATION:
- ALWAYS use customer's name if known
- Reference loan purpose if mentioned ("for your home renovation")
- Acknowledge what they just said before responding

TONE BY AGENT:
- SALES: Warm, friendly, uses emojis sparingly 😊
- VERIFICATION: Formal, brief, NO emojis
- UNDERWRITING: Neutral, factual, NO excitement
- SANCTION: Warm for approval 🎉, empathetic for rejection

DEMO READINESS (CRITICAL):
- NEVER mention "stage", "agent", "system", "state"
- NEVER use technical terms or variable names
- NEVER sound robotic or scripted
- Always appear as ONE seamless smart assistant
- Avoid: "Your request has been noted" / "Please wait while I process"
- Prefer: Natural, human-like responses

CONTINUITY:
- Don't repeat questions already answered
- Reference recent conversation naturally
- If information is in context, use it

Generate your response now (keep it SHORT and NATURAL):"""

    def _get_fallback_response(self, state: ConversationState) -> str:
        """
        Get a fallback response if LLM fails.
        
        PHASE 6: Natural, human-like fallbacks that don't break immersion.
        Customized by agent type to maintain personality consistency.
        """
        name = state.user_name or ""
        greeting = f", {name}" if name else ""
        
        fallbacks = {
            WorkerAgentType.SALES: f"Hi{greeting}! I'm here to help you find the right loan. What are you looking for today?",
            WorkerAgentType.VERIFICATION: "Please share the required details to continue.",
            WorkerAgentType.UNDERWRITING: "Your application is being reviewed. I'll have an update shortly.",
            WorkerAgentType.SANCTION: "Your application has been processed. Please see the details above.",
        }
        return fallbacks.get(self.agent_type, f"Hi{greeting}! How can I help you today?")


# ================================================================================
# MASTER AGENT
# ================================================================================
# The Master Agent is the ORCHESTRATOR that:
# 1. Reads current_stage from state
# 2. Maps stage → Worker Agent (DETERMINISTICALLY)
# 3. Prepares instructions for the Worker Agent
# 4. Returns the Worker Agent's response
#
# CRITICAL: The Master Agent NEVER changes current_stage.
# Stage transitions are handled ONLY by StageRouter (Phase 1).

class MasterAgent:
    """
    The Master Agent orchestrates Worker Agents based on current stage.
    
    RESPONSIBILITIES:
    1. Read current_stage from shared state
    2. Select the appropriate Worker Agent (DETERMINISTIC mapping)
    3. Prepare stage-specific instructions
    4. Delegate response generation to Worker Agent
    5. Return the response
    
    NOT RESPONSIBLE FOR:
    - Changing current_stage (handled by StageRouter)
    - Performing verification logic
    - Making underwriting decisions
    - Calling external APIs
    
    This separation ensures:
    - Flow control remains DETERMINISTIC
    - Personality/responses are NATURAL
    - Each concern is handled by the right component
    """
    
    def __init__(self, gemini_api_key: str):
        """
        Initialize the Master Agent with all Worker Agents.
        
        Args:
            gemini_api_key: API key for LLM access
        """
        # Initialize the LLM (shared by all agents for efficiency)
        self.llm = ChatGoogleGenerativeAI(
            model="gemini-2.0-flash",
            google_api_key=gemini_api_key,
            temperature=0.7,
            convert_system_message_to_human=True
        )
        
        # Initialize Worker Agents
        # Each agent is an LLM wrapper with a specific personality
        self.worker_agents: Dict[WorkerAgentType, WorkerAgent] = {
            WorkerAgentType.SALES: WorkerAgent(WorkerAgentType.SALES, self.llm),
            WorkerAgentType.VERIFICATION: WorkerAgent(WorkerAgentType.VERIFICATION, self.llm),
            WorkerAgentType.UNDERWRITING: WorkerAgent(WorkerAgentType.UNDERWRITING, self.llm),
            WorkerAgentType.SANCTION: WorkerAgent(WorkerAgentType.SANCTION, self.llm),
        }
        
        print("\n" + "="*60)
        print("🎯 MASTER AGENT INITIALIZED (Phase 2)")
        print("="*60)
        print("📍 Worker Agents: Sales, Verification, Underwriting, Sanction")
        print("🔀 Routing: Deterministic stage → agent mapping")
        print("💬 Response: Personality-driven Worker Agents")
        print("="*60 + "\n")
    
    def get_agent_for_stage(self, stage: ConversationStage) -> WorkerAgentType:
        """
        Get the Worker Agent type for a given stage.
        
        This mapping is EXPLICIT and DETERMINISTIC.
        No LLM decision-making involved.
        
        Args:
            stage: Current conversation stage
            
        Returns:
            WorkerAgentType that handles this stage
        """
        agent_type = STAGE_TO_AGENT_MAP.get(stage, WorkerAgentType.SALES)
        print(f"🎯 Stage {stage.value} → {agent_type.value.upper()} Agent")
        return agent_type
    
    def get_stage_instruction(self, stage: ConversationStage) -> str:
        """
        Get the instruction for the current stage.
        
        Args:
            stage: Current conversation stage
            
        Returns:
            Instruction string for the Worker Agent
        """
        return STAGE_SPECIFIC_INSTRUCTIONS.get(stage, "Assist the customer with their query.")
    
    async def orchestrate(
        self,
        state: ConversationState,
        user_message: str
    ) -> Dict[str, Any]:
        """
        Orchestrate the response generation.
        
        This is the MAIN ENTRY POINT for the Master Agent.
        
        Steps:
        1. Read current_stage from state
        2. Map stage → Worker Agent (DETERMINISTIC)
        3. Get stage-specific instructions
        4. Delegate to Worker Agent
        5. Return response and metadata
        
        CRITICAL: This method does NOT change current_stage.
        Stage transitions are handled by StageRouter before this is called.
        
        Args:
            state: Current conversation state (already routed by StageRouter)
            user_message: The user's message
            
        Returns:
            Dict with response and agent metadata
        """
        # Step 1: Read current stage (set by StageRouter in Phase 1)
        current_stage = state.current_stage
        
        # Step 2: Map stage to Worker Agent (DETERMINISTIC)
        agent_type = self.get_agent_for_stage(current_stage)
        worker_agent = self.worker_agents[agent_type]
        
        # Step 3: Get stage-specific instruction
        stage_instruction = self.get_stage_instruction(current_stage)
        
        # Step 4: Delegate to Worker Agent
        print(f"📤 Delegating to {agent_type.value.upper()} Agent...")
        
        response = await worker_agent.generate_response(
            state=state,
            stage_instruction=stage_instruction,
            user_message=user_message,
            conversation_history=state.conversation_history
        )
        
        print(f"📥 {agent_type.value.upper()} Agent responded")
        
        # Step 5: Return response with metadata
        return {
            "response": response,
            "agent_type": agent_type.value,
            "stage": current_stage.value,
        }


# ================================================================================
# FACTORY FUNCTION
# ================================================================================

def create_master_agent() -> MasterAgent:
    """
    Create a Master Agent instance.
    
    Returns:
        Configured MasterAgent
        
    Raises:
        ValueError: If GEMINI_API_KEY not set
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable not set")
    
    return MasterAgent(api_key)


# ================================================================================
# HELPER: Get agent info for admin dashboard
# ================================================================================

def get_agent_info(stage: ConversationStage) -> Dict[str, str]:
    """
    Get information about the agent handling a stage.
    Useful for admin dashboard display.
    
    PHASE 6 UPDATE:
    ---------------
    Added personality summaries for better admin visibility
    into how each agent communicates differently.
    
    Args:
        stage: Current conversation stage
        
    Returns:
        Dict with agent name, type, description, and personality
    """
    agent_type = STAGE_TO_AGENT_MAP.get(stage, WorkerAgentType.SALES)
    
    # Phase 6: Detailed descriptions matching refined personalities
    descriptions = {
        WorkerAgentType.SALES: "Builds rapport, understands needs, handles hesitation warmly",
        WorkerAgentType.VERIFICATION: "Collects KYC data efficiently with formal, brief communication",
        WorkerAgentType.UNDERWRITING: "Presents credit assessment facts neutrally and professionally",
        WorkerAgentType.SANCTION: "Delivers final decision - celebratory for approvals, empathetic for rejections",
    }
    
    # Phase 6: Personality summaries for admin insight
    personalities = {
        WorkerAgentType.SALES: "Warm • Empathetic • Persuasive • Uses emojis",
        WorkerAgentType.VERIFICATION: "Formal • Brief • No emojis • Task-focused",
        WorkerAgentType.UNDERWRITING: "Neutral • Factual • Professional • Data-driven",
        WorkerAgentType.SANCTION: "Official • Warm (approval) / Empathetic (rejection)",
    }
    
    return {
        "agent_type": agent_type.value,
        "agent_name": f"{agent_type.value.title()} Agent",
        "description": descriptions.get(agent_type, "Assists with customer queries"),
        "personality": personalities.get(agent_type, "Professional"),
    }
