"""
sales_agent.py
==============

Production worker agent for the **sales & advisory** stages of the
lending chatbot.

Covered States
--------------
- ``GREETING``          — welcome and capture applicant name.
- ``PURPOSE``           — discover the loan purpose / product category.
- ``LOAN_AMOUNT``       — capture the requested amount and compute indicative EMI.
- ``OFFER_PRESENTATION``— present personalised loan offers with EMI breakdowns.
- ``TENURE_SELECTION``  — help the user pick a tenure; handle affordability concerns.

Responsibilities
----------------
1. **Discover loan purpose** — map free-text input to a canonical category.
2. **Explain EMI and tenure** — use the deterministic ``emi_calculator`` to
   show monthly payments, total interest, and cost comparisons.
3. **Handle affordability concerns** — if EMI > 50 % FOIR, proactively
   suggest a longer tenure or lower amount.
4. **Suggest alternatives** — generate a comparison table of 3 tenure
   options so the user can make an informed choice.
5. **Dynamic responses** — all user-facing messages are composed from
   parameterised templates; no hard-coded strings in business logic.

Design Notes
------------
- **No AI for calculations** — all EMI, interest, and affordability numbers
  come from pure arithmetic in ``backend.core.emi_calculator``.
- Templates are defined in ``TEMPLATES`` at the bottom of this file for
  locality; they can be moved to a shared registry later.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from backend.agents.base_agent import AgentResult, BaseAgent
from backend.core.emi_calculator import (
    calculate_emi,
    check_affordability,
    compute_total_interest,
)


# ═══════════════════════════════════════════════════════════════════════════
# Loan-Purpose Mapping
# ═══════════════════════════════════════════════════════════════════════════

# Maps free-text synonyms to canonical purpose keys accepted by the
# state-machine validator.

PURPOSE_SYNONYMS: Dict[str, str] = {
    # Personal
    "personal":     "personal",
    "pl":           "personal",
    "personal loan":"personal",
    "cash":         "personal",
    "emergency":    "personal",
    "medical":      "personal",
    "wedding":      "personal",
    "travel":       "personal",
    # Home
    "home":         "home",
    "house":        "home",
    "housing":      "home",
    "home loan":    "home",
    "property":     "home",
    "flat":         "home",
    "apartment":    "home",
    "construction": "home",
    # Auto
    "auto":         "auto",
    "car":          "auto",
    "vehicle":      "auto",
    "bike":         "auto",
    "two wheeler":  "auto",
    "car loan":     "auto",
    # Business
    "business":     "business",
    "msme":         "business",
    "working capital": "business",
    "startup":      "business",
    "enterprise":   "business",
    # Education
    "education":    "education",
    "study":        "education",
    "student":      "education",
    "college":      "education",
    "university":   "education",
    "course":       "education",
    # Gold
    "gold":         "gold",
    "gold loan":    "gold",
    "jewellery":    "gold",
    "jewelry":      "gold",
}


# ═══════════════════════════════════════════════════════════════════════════
# Default Interest Rates (indicative, per product category)
# ═══════════════════════════════════════════════════════════════════════════

DEFAULT_RATES: Dict[str, float] = {
    "personal":  12.0,
    "home":       8.5,
    "auto":       9.5,
    "business":  14.0,
    "education": 10.0,
    "gold":       9.0,
}

# Standard tenure options per product (in months)
TENURE_OPTIONS: Dict[str, List[int]] = {
    "personal":  [12, 24, 36, 48, 60],
    "home":      [60, 120, 180, 240, 360],
    "auto":      [12, 24, 36, 48, 60, 84],
    "business":  [12, 24, 36, 48, 60],
    "education": [36, 48, 60, 84, 120],
    "gold":      [12, 24, 36],
}


# ═══════════════════════════════════════════════════════════════════════════
# EMI Comparison Row (for multi-tenure tables)
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class EMIOption:
    """One row in the tenure-comparison table."""
    tenure_months: int
    emi: float
    total_interest: float
    total_payment: float
    affordable: bool


# ═══════════════════════════════════════════════════════════════════════════
# Dynamic Response Templates
# ═══════════════════════════════════════════════════════════════════════════
#
# All user-facing text is generated by filling ``{placeholders}`` in these
# templates.  Business logic NEVER contains raw strings shown to users.
# ═══════════════════════════════════════════════════════════════════════════

TEMPLATES: Dict[str, str] = {

    # ── Greeting stage ──────────────────────────────────────────────────
    "welcome": (
        "Hello{name_part}! 👋 Welcome to **Tata Capital**.\n\n"
        "I'm your AI lending assistant and I'll guide you through the "
        "entire loan process — from choosing the right product to getting "
        "your sanction letter.\n\n"
        "Let's get started! What is your **full name**?"
    ),
    "name_captured": (
        "Nice to meet you, **{name}**! 🤝\n\n"
        "What type of loan are you looking for today?\n"
        "Options: **Personal** · **Home** · **Auto** · **Business** · "
        "**Education** · **Gold**"
    ),

    # ── Purpose discovery ───────────────────────────────────────────────
    "purpose_confirmed": (
        "Great choice! A **{purpose_title} Loan** is a popular option.\n\n"
        "Here's a quick overview:\n"
        "• Interest rate starting from **{rate}% p.a.**\n"
        "• Tenures available: {tenures}\n"
        "• Minimal documentation required\n\n"
        "How much loan amount do you need? (₹10,000 – ₹5 Cr)"
    ),
    "purpose_unknown": (
        "I didn't quite catch that. Could you tell me the **type of loan** "
        "you're interested in?\n\n"
        "Choose from: **Personal** · **Home** · **Auto** · **Business** · "
        "**Education** · **Gold**"
    ),

    # ── Loan amount ─────────────────────────────────────────────────────
    "amount_captured": (
        "Got it — **₹{amount_fmt}** for a {purpose_title} Loan.\n\n"
        "📊 **Indicative EMI Breakdown**\n\n"
        "{emi_table}\n\n"
        "💡 The longer the tenure, the lower your EMI — but the total "
        "interest paid increases.\n\n"
        "Would you like to proceed with this amount, or adjust it?"
    ),
    "amount_invalid": (
        "The loan amount should be between **₹10,000** and **₹5,00,00,000**.\n"
        "Please enter a valid amount."
    ),

    # ── EMI explanation ─────────────────────────────────────────────────
    "emi_explanation": (
        "📖 **What is EMI?**\n\n"
        "EMI stands for **Equated Monthly Instalment** — the fixed amount "
        "you pay every month until the loan is fully repaid.\n\n"
        "Your EMI has two parts:\n"
        "1️⃣ **Principal** — reduces your outstanding loan balance.\n"
        "2️⃣ **Interest** — the cost of borrowing.\n\n"
        "Early EMIs have a higher interest component. Over time, more of "
        "your EMI goes toward repaying the principal.\n\n"
        "📊 For your loan of **₹{amount_fmt}** at **{rate}% p.a.**:\n"
        "{emi_table}"
    ),

    # ── Affordability concern ───────────────────────────────────────────
    "affordability_warning": (
        "⚠️ **Affordability Alert**\n\n"
        "At your stated income of **₹{income_fmt}/month**, an EMI of "
        "**₹{emi_fmt}** would use **{foir_pct}%** of your income — "
        "above the recommended 50% limit.\n\n"
        "💬 Many customers choose smaller EMIs to stay comfortable — "
        "there's no rush, and a longer tenure keeps things easy on your "
        "wallet.\n\n"
        "Here are some options to make it more manageable:\n\n"
        "{alternatives}\n\n"
        "🏦 _This estimate follows standard banking affordability guidelines._\n\n"
        "Would you like to adjust your loan amount or tenure?"
    ),
    "affordability_ok": (
        "✅ **Affordability Check Passed**\n\n"
        "Your EMI of **₹{emi_fmt}** is **{foir_pct}%** of your monthly "
        "income — well within the safe limit.\n\n"
        "💚 This EMI fits comfortably within your income range. "
        "You're in great shape to proceed!\n\n"
        "🏦 _This estimate follows standard banking affordability guidelines._"
    ),

    # ── Offers ──────────────────────────────────────────────────────────
    "offers_presented": (
        "🎉 **Your Personalised Loan Offers**\n\n"
        "{offers_table}\n\n"
        "Select an offer by its **number** (1–{offer_count}), or type "
        "**compare** to see a side-by-side breakdown."
    ),
    "offer_selected": (
        "You've selected **Offer #{offer_num}**:\n\n"
        "• Amount: **₹{amount_fmt}**\n"
        "• Tenure: **{tenure} months**\n"
        "• EMI: **₹{emi_fmt}/month**\n"
        "• Rate: **{rate}% p.a.**\n"
        "• Total interest: **₹{interest_fmt}**\n\n"
        "Now choose your preferred tenure — or confirm the one above."
    ),

    # ── Tenure selection ────────────────────────────────────────────────
    "tenure_comparison": (
        "📊 **Tenure Comparison** (₹{amount_fmt} at {rate}% p.a.)\n\n"
        "{comparison_table}\n\n"
        "Pick the tenure that suits your budget. Shorter tenures save "
        "interest; longer tenures reduce monthly pressure."
    ),
    "tenure_confirmed": (
        "Locked in: **{tenure} months** at **₹{emi_fmt}/month**.\n\n"
        "Total repayment: ₹{total_fmt} (interest: ₹{interest_fmt}).\n\n"
        "Please **accept** or **reject** this final offer."
    ),

    # ── Hesitation nudge ────────────────────────────────────────────────
    "hesitation_nudge": (
        "I understand — choosing the right loan setup is important! 🤔\n\n"
        "💬 Many customers choose smaller EMIs to stay comfortable. "
        "There's absolutely no pressure to pick the shortest tenure.\n\n"
        "Here's a quick comparison so you can see how different tenures "
        "affect your monthly payment:\n\n"
        "{comparison_table}\n\n"
        "🏦 _This estimate follows standard banking affordability guidelines._\n\n"
        "Pick whatever feels right for your budget!"
    ),

    # ── Fallback ────────────────────────────────────────────────────────
    "fallback": (
        "I didn't quite understand that. Could you rephrase?\n\n"
        "💡 Tip: {tip}"
    ),
}


# ═══════════════════════════════════════════════════════════════════════════
# Helper Functions (pure, no side-effects)
# ═══════════════════════════════════════════════════════════════════════════

def _fmt(n: float) -> str:
    """Format a number Indian-style with commas (approx)."""
    if n >= 1_00_00_000:
        return f"{n / 1_00_00_000:,.2f} Cr"
    if n >= 1_00_000:
        return f"{n / 1_00_000:,.2f} L"
    return f"{n:,.0f}"


def _parse_amount(text: str) -> Optional[float]:
    """
    Extract a loan amount from free-text input.

    Handles patterns like:
    - "500000", "5,00,000", "₹5,00,000"
    - "5 lakh", "5L", "50 lac"
    - "1 crore", "1.5 cr", "1.5Cr"
    """
    text = text.strip().lower().replace("₹", "").replace(",", "").replace(" ", "")

    # Crore pattern
    m = re.match(r"^(\d+\.?\d*)\s*(crore|cr)s?$", text)
    if m:
        return float(m.group(1)) * 1_00_00_000

    # Lakh pattern
    m = re.match(r"^(\d+\.?\d*)\s*(lakh|lac|l)s?$", text)
    if m:
        return float(m.group(1)) * 1_00_000

    # Thousand pattern
    m = re.match(r"^(\d+\.?\d*)\s*(thousand|k)s?$", text)
    if m:
        return float(m.group(1)) * 1_000

    # Plain number
    m = re.match(r"^(\d+\.?\d*)$", text)
    if m:
        return float(m.group(1))

    return None


def _detect_purpose(text: str) -> Optional[str]:
    """Map free-text input to a canonical loan-purpose key."""
    normalised = text.strip().lower()
    # Direct lookup
    if normalised in PURPOSE_SYNONYMS:
        return PURPOSE_SYNONYMS[normalised]
    # Substring search
    for keyword, purpose in PURPOSE_SYNONYMS.items():
        if keyword in normalised:
            return purpose
    return None


def _build_emi_table(
    principal: float,
    rate: float,
    tenures: List[int],
    income: Optional[float] = None,
) -> Tuple[str, List[EMIOption]]:
    """
    Build a Markdown comparison table for multiple tenure options.

    Returns the formatted table string AND the list of ``EMIOption`` rows.
    """
    options: List[EMIOption] = []
    for t in tenures:
        emi = calculate_emi(principal, rate, t)
        total_interest = compute_total_interest(principal, rate, t)
        total = round(principal + total_interest, 2)
        affordable = check_affordability(income, emi) if income and income > 0 else True
        options.append(EMIOption(t, emi, total_interest, total, affordable))

    lines = ["| Tenure | EMI/month | Total Interest | Total Payment | Status |"]
    lines.append("|--------|-----------|----------------|---------------|--------|")
    for o in options:
        status = "✅" if o.affordable else "⚠️"
        lines.append(
            f"| {o.tenure_months} mo | ₹{_fmt(o.emi)} | ₹{_fmt(o.total_interest)} "
            f"| ₹{_fmt(o.total_payment)} | {status} |"
        )
    return "\n".join(lines), options


def _build_alternatives(
    principal: float, rate: float, income: float, current_tenure: int
) -> str:
    """Suggest reduced amounts or longer tenures to fix affordability."""
    suggestions: List[str] = []

    # Option A — extend tenure
    for t in (current_tenure + 12, current_tenure + 24, current_tenure + 36):
        alt_emi = calculate_emi(principal, rate, t)
        if check_affordability(income, alt_emi):
            suggestions.append(
                f"📌 **Extend to {t} months** → EMI drops to ₹{_fmt(alt_emi)}/month"
            )
            break

    # Option B — reduce amount (try 80%, 60%)
    for pct in (0.80, 0.60):
        reduced = round(principal * pct)
        alt_emi = calculate_emi(reduced, rate, current_tenure)
        if check_affordability(income, alt_emi):
            suggestions.append(
                f"📌 **Reduce amount to ₹{_fmt(reduced)}** → EMI falls to ₹{_fmt(alt_emi)}/month"
            )
            break

    return "\n".join(suggestions) if suggestions else "Consider co-applying with a guarantor to improve eligibility."


def _extract_name(text: str) -> Optional[str]:
    """Best-effort name extraction from a short user message."""
    # Strip common prefixes
    cleaned = re.sub(
        r"^(my name is|i am|i'm|this is|call me|it's|its)\s+",
        "",
        text.strip(),
        flags=re.IGNORECASE,
    )
    # Take up to 4 words, alphabetic only
    words = [w for w in cleaned.split() if re.match(r"^[a-zA-Z]+$", w)]
    if words:
        return " ".join(words[:4]).title()
    return None


def _render(template_key: str, **kwargs) -> str:
    """Render a response template, silently ignoring missing keys."""
    tpl = TEMPLATES.get(template_key, "")
    try:
        return tpl.format(**kwargs)
    except KeyError:
        return tpl


# ═══════════════════════════════════════════════════════════════════════════
# Sales Agent
# ═══════════════════════════════════════════════════════════════════════════

class SalesAgent(BaseAgent):
    """
    Handles greeting, purpose discovery, loan amount capture, offer
    presentation, and tenure selection — all powered by deterministic
    EMI calculations and parameterised response templates.
    """

    def __init__(self) -> None:
        super().__init__(name="sales")

    async def process(
        self,
        session_id: str,
        user_message: str,
        context: Dict[str, Any],
    ) -> AgentResult:
        """
        Route to the correct handler based on the current conversation state.
        """
        state = context.get("state", "")
        collected = context.get("collected_data", {})
        self.logger.info("SalesAgent | session=%s state=%s", session_id, state)

        handler = {
            "greeting":           self._handle_greeting,
            "purpose":            self._handle_purpose,
            "loan_amount":        self._handle_loan_amount,
            "offer_presentation": self._handle_offers,
            "tenure_selection":   self._handle_tenure,
        }.get(state, self._handle_fallback)

        return await handler(session_id, user_message, collected, context)

    # ── GREETING ────────────────────────────────────────────────────────

    async def _handle_greeting(
        self, session_id: str, msg: str, collected: Dict, ctx: Dict
    ) -> AgentResult:
        """Capture applicant name and welcome them."""
        name = _extract_name(msg)
        if not name:
            return AgentResult(
                success=True,
                message=_render("welcome", name_part=""),
                data={},
            )

        return AgentResult(
            success=True,
            message=_render("name_captured", name=name),
            data={"applicant_name": name},
        )

    # ── PURPOSE ─────────────────────────────────────────────────────────

    async def _handle_purpose(
        self, session_id: str, msg: str, collected: Dict, ctx: Dict
    ) -> AgentResult:
        """Discover the loan purpose from the user's message."""

        # Check for EMI explanation requests
        if any(kw in msg.lower() for kw in ("what is emi", "explain emi", "emi meaning", "emi kya")):
            return await self._explain_emi(collected)

        purpose = _detect_purpose(msg)
        if not purpose:
            return AgentResult(
                success=True,
                message=_render("purpose_unknown"),
                data={},
            )

        rate = DEFAULT_RATES.get(purpose, 12.0)
        tenures = TENURE_OPTIONS.get(purpose, [12, 24, 36, 48, 60])
        tenure_str = " · ".join(f"{t} mo" for t in tenures)

        return AgentResult(
            success=True,
            message=_render(
                "purpose_confirmed",
                purpose_title=purpose.title(),
                rate=rate,
                tenures=tenure_str,
            ),
            data={"loan_purpose": purpose},
        )

    # ── LOAN AMOUNT ─────────────────────────────────────────────────────

    async def _handle_loan_amount(
        self, session_id: str, msg: str, collected: Dict, ctx: Dict
    ) -> AgentResult:
        """Capture the requested loan amount and show indicative EMI table."""

        # EMI explanation mid-stage
        if any(kw in msg.lower() for kw in ("what is emi", "explain emi", "emi meaning")):
            return await self._explain_emi(collected)

        amount = _parse_amount(msg)
        if amount is None:
            return AgentResult(
                success=True,
                message=_render("amount_invalid"),
                data={},
            )

        if amount < 10_000 or amount > 5_00_00_000:
            return AgentResult(
                success=True,
                message=_render("amount_invalid"),
                data={},
            )

        purpose = collected.get("loan_purpose", "personal")
        rate = DEFAULT_RATES.get(purpose, 12.0)
        tenures = TENURE_OPTIONS.get(purpose, [12, 24, 36, 48, 60])
        income = collected.get("monthly_income")

        emi_table, options = _build_emi_table(amount, rate, tenures, income)

        return AgentResult(
            success=True,
            message=_render(
                "amount_captured",
                amount_fmt=_fmt(amount),
                purpose_title=purpose.title(),
                emi_table=emi_table,
            ),
            data={
                "loan_amount": amount,
                "requested_amount": amount,
                "indicative_rate": rate,
                "emi_options": [
                    {
                        "tenure": o.tenure_months,
                        "emi": o.emi,
                        "total_interest": o.total_interest,
                        "total_payment": o.total_payment,
                        "affordable": o.affordable,
                    }
                    for o in options
                ],
            },
        )

    # ── OFFER PRESENTATION ──────────────────────────────────────────────

    async def _handle_offers(
        self, session_id: str, msg: str, collected: Dict, ctx: Dict
    ) -> AgentResult:
        """Present loan offers and handle offer selection."""
        offers = collected.get("loan_offers", [])

        # If the user selects an offer by number
        selection = re.match(r"^(\d+)$", msg.strip())
        if selection and offers:
            idx = int(selection.group(1)) - 1
            if 0 <= idx < len(offers):
                offer = offers[idx]
                return AgentResult(
                    success=True,
                    message=_render(
                        "offer_selected",
                        offer_num=idx + 1,
                        amount_fmt=_fmt(offer.get("amount", 0)),
                        tenure=offer.get("tenure", 0),
                        emi_fmt=_fmt(offer.get("emi", 0)),
                        rate=offer.get("rate", 0),
                        interest_fmt=_fmt(offer.get("total_interest", 0)),
                    ),
                    data={"selected_offer_id": offer.get("id", str(idx + 1))},
                )

        # Build the offers table
        if offers:
            lines = ["| # | Amount | Tenure | EMI/mo | Rate |"]
            lines.append("|---|--------|--------|--------|------|")
            for i, o in enumerate(offers, 1):
                lines.append(
                    f"| {i} | ₹{_fmt(o.get('amount', 0))} "
                    f"| {o.get('tenure', 0)} mo "
                    f"| ₹{_fmt(o.get('emi', 0))} "
                    f"| {o.get('rate', 0)}% |"
                )
            table = "\n".join(lines)
            return AgentResult(
                success=True,
                message=_render(
                    "offers_presented",
                    offers_table=table,
                    offer_count=len(offers),
                ),
                data={},
            )

        # No offers generated yet — auto-generate from collected data
        amount = collected.get("loan_amount", 0)
        purpose = collected.get("loan_purpose", "personal")
        rate = DEFAULT_RATES.get(purpose, 12.0)
        tenures = TENURE_OPTIONS.get(purpose, [12, 24, 36, 48, 60])

        generated_offers: List[Dict[str, Any]] = []
        for t in tenures[:3]:  # top 3 tenure options
            emi = calculate_emi(amount, rate, t)
            interest = compute_total_interest(amount, rate, t)
            generated_offers.append({
                "id": f"OFFER-{purpose.upper()}-{t}",
                "amount": amount,
                "tenure": t,
                "emi": emi,
                "rate": rate,
                "total_interest": interest,
            })

        lines = ["| # | Amount | Tenure | EMI/mo | Rate |"]
        lines.append("|---|--------|--------|--------|------|")
        for i, o in enumerate(generated_offers, 1):
            lines.append(
                f"| {i} | ₹{_fmt(o['amount'])} | {o['tenure']} mo "
                f"| ₹{_fmt(o['emi'])} | {o['rate']}% |"
            )
        table = "\n".join(lines)

        return AgentResult(
            success=True,
            message=_render(
                "offers_presented",
                offers_table=table,
                offer_count=len(generated_offers),
            ),
            data={"loan_offers": generated_offers},
        )

    # ── TENURE SELECTION ────────────────────────────────────────────────

    async def _handle_tenure(
        self, session_id: str, msg: str, collected: Dict, ctx: Dict
    ) -> AgentResult:
        """Help the user select a tenure; handle affordability concerns."""
        amount = collected.get("loan_amount", 0)
        purpose = collected.get("loan_purpose", "personal")
        rate = DEFAULT_RATES.get(purpose, 12.0)
        income = collected.get("monthly_income")
        tenures = TENURE_OPTIONS.get(purpose, [12, 24, 36, 48, 60])

        # ── Hesitation detection ────────────────────────────────────────
        hesitation_cues = (
            "not sure", "unsure", "confused", "too much", "too high",
            "expensive", "can't afford", "afford", "worried", "scary",
            "nervous", "think about", "need time", "hmm", "idk",
            "don't know", "which one", "what should",
        )
        if any(cue in msg.lower() for cue in hesitation_cues):
            table, _ = _build_emi_table(amount, rate, tenures, income)
            return AgentResult(
                success=True,
                message=_render(
                    "hesitation_nudge",
                    comparison_table=table,
                ),
                data={},
            )

        # If user asks for comparison
        if any(kw in msg.lower() for kw in ("compare", "comparison", "options", "show me")):
            table, _ = _build_emi_table(amount, rate, tenures, income)
            return AgentResult(
                success=True,
                message=_render(
                    "tenure_comparison",
                    amount_fmt=_fmt(amount),
                    rate=rate,
                    comparison_table=table,
                ),
                data={},
            )

        # Try to parse a tenure value
        m = re.search(r"(\d+)", msg)
        if not m:
            table, _ = _build_emi_table(amount, rate, tenures, income)
            return AgentResult(
                success=True,
                message=_render(
                    "tenure_comparison",
                    amount_fmt=_fmt(amount),
                    rate=rate,
                    comparison_table=table,
                ),
                data={},
            )

        tenure = int(m.group(1))
        emi = calculate_emi(amount, rate, tenure)
        total_interest = compute_total_interest(amount, rate, tenure)
        total = round(amount + total_interest, 2)

        # Affordability check (if income is known)
        if income and income > 0:
            foir = round(emi / income * 100, 1)
            if not check_affordability(income, emi):
                alternatives = _build_alternatives(amount, rate, income, tenure)
                return AgentResult(
                    success=True,
                    message=_render(
                        "affordability_warning",
                        income_fmt=_fmt(income),
                        emi_fmt=_fmt(emi),
                        foir_pct=foir,
                        alternatives=alternatives,
                    ),
                    data={},
                )
            # Passes affordability
            data_out = {"selected_tenure": tenure}
            affordability_msg = _render(
                "affordability_ok",
                emi_fmt=_fmt(emi),
                foir_pct=foir,
            )
        else:
            data_out = {"selected_tenure": tenure}
            affordability_msg = ""

        confirmation = _render(
            "tenure_confirmed",
            tenure=tenure,
            emi_fmt=_fmt(emi),
            total_fmt=_fmt(total),
            interest_fmt=_fmt(total_interest),
        )

        full_msg = f"{affordability_msg}\n\n{confirmation}" if affordability_msg else confirmation

        return AgentResult(
            success=True,
            message=full_msg,
            data=data_out,
        )

    # ── EMI Explanation (reusable) ──────────────────────────────────────

    async def _explain_emi(self, collected: Dict) -> AgentResult:
        """Return a plain-language EMI explanation with numbers if available."""
        amount = collected.get("loan_amount")
        purpose = collected.get("loan_purpose", "personal")
        rate = DEFAULT_RATES.get(purpose, 12.0)
        tenures = TENURE_OPTIONS.get(purpose, [12, 24, 36, 48, 60])
        income = collected.get("monthly_income")

        if amount and amount > 0:
            table, _ = _build_emi_table(amount, rate, tenures, income)
            return AgentResult(
                success=True,
                message=_render(
                    "emi_explanation",
                    amount_fmt=_fmt(amount),
                    rate=rate,
                    emi_table=table,
                ),
                data={},
            )

        # Generic explanation without numbers
        return AgentResult(
            success=True,
            message=(
                "📖 **What is EMI?**\n\n"
                "EMI stands for **Equated Monthly Instalment** — the fixed "
                "amount you pay every month until the loan is fully repaid.\n\n"
                "Each EMI includes a **principal** portion (reduces your loan "
                "balance) and an **interest** portion (cost of borrowing).\n\n"
                "Once we know your loan amount, I'll show you exact EMI "
                "figures for different tenures!"
            ),
            data={},
        )

    # ── Fallback ────────────────────────────────────────────────────────

    async def _handle_fallback(
        self, session_id: str, msg: str, collected: Dict, ctx: Dict
    ) -> AgentResult:
        """Generic fallback when the state doesn't match a known handler."""
        state = ctx.get("state", "unknown")
        tips = {
            "greeting":    "Tell me your full name to get started.",
            "purpose":     "Type your loan type: Personal, Home, Auto, Business, Education, or Gold.",
            "loan_amount": "Enter the amount you need, e.g. '5 lakh' or '500000'.",
        }
        tip = tips.get(state, "Type **help** for guidance.")
        return AgentResult(
            success=True,
            message=_render("fallback", tip=tip),
            data={},
        )
